name: Install Prerequisites on Ubuntu

runs:
  using: composite

  steps:
    - name: Install packages
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq \
             libboost-dev \
             libgdal-dev \
             libgeos++-dev \
             libproj-dev \
             nodejs
      shell: bash
    - name: Install from git
      run: |
        git clone --quiet --depth 1 https://github.com/mapbox/protozero.git ../protozero
        git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
      shell: bash

